Repository ISIS-3510-Mobiles/Kotlin, pull requests merged in 2024-12, with the labels that each got.

#41 The adjustments and corrections for Sprint 3 have been successfully completed.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ecostyle/view/ListFragment.kt
  app/src/main/java/com/example/ecostyle/view/ProfileFragment.kt
  app/src/main/java/com/example/ecostyle/view/PublishItemFragment.kt
  app/src/main/java/com/example/ecostyle/viewmodel/ProductViewModel.kt
  app/src/main/res/xml/file_paths.xml
Labels: bug, sprint 3

#42 Fix Connectivity Issues and Implement Performance Enhancements
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ecostyle/adapter/ProductAdapter.kt
  app/src/main/java/com/example/ecostyle/view/LikesFragment.kt
  app/src/main/java/com/example/ecostyle/view/ListFragment.kt
  app/src/main/java/com/example/ecostyle/view/ProductDetailFragment.kt
  app/src/main/java/com/example/ecostyle/view/ProfileFragment.kt
  app/src/main/java/com/example/ecostyle/view/PublishItemFragment.kt
  app/src/main/java/com/example/ecostyle/viewmodel/ProductViewModel.kt
  app/src/main/java/com/example/ecostyle/viewmodel/UploadWorker.kt
  app/src/main/res/xml/file_paths.xml
Labels: bug, sprint 3

#44 Pull Request: Sprint 4 Implementation - Sales and Purchase History
  .idea/other.xml
  README.md
  app/src/main/java/com/example/ecostyle/Repository/ProductRepository.kt
  app/src/main/java/com/example/ecostyle/activity/HomeActivity.kt
  app/src/main/java/com/example/ecostyle/adapter/HistoryAdapter.kt
  app/src/main/java/com/example/ecostyle/view/CheckoutFragment.kt
  app/src/main/java/com/example/ecostyle/view/HistoryFragment.kt
  app/src/main/java/com/example/ecostyle/view/PaymentFragment.kt
  app/src/main/java/com/example/ecostyle/view/PublishItemFragment.kt
  app/src/main/java/com/example/ecostyle/viewmodel/PublishItemViewModel.kt
  app/src/main/res/drawable/ic_history.png
  app/src/main/res/layout/activity_item_product_card_history.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_publish_item.xml
  app/src/main/res/menu/activity_main_drawer.xml
Labels: enhancement, sprint 4

#47 Develop
  .idea/other.xml
  app/src/main/java/com/example/ecostyle/Repository/ProductRepository.kt
  app/src/main/java/com/example/ecostyle/activity/HomeActivity.kt
  app/src/main/java/com/example/ecostyle/adapter/HistoryAdapter.kt
  app/src/main/java/com/example/ecostyle/view/CheckoutFragment.kt
  app/src/main/java/com/example/ecostyle/view/HistoryFragment.kt
  app/src/main/java/com/example/ecostyle/view/PaymentFragment.kt
  app/src/main/java/com/example/ecostyle/view/PublishItemFragment.kt
  app/src/main/java/com/example/ecostyle/viewmodel/PublishItemViewModel.kt
  app/src/main/res/drawable/ic_history.png
  app/src/main/res/layout/activity_item_product_card_history.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_publish_item.xml
  app/src/main/res/menu/activity_main_drawer.xml
Labels: sprint 4

#60 Develop
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/example/ecostyle/Repository/ProductRepository.kt
  app/src/main/java/com/example/ecostyle/view/ListFragment.kt
  app/src/main/java/com/example/ecostyle/view/PublishItemFragment.kt
  app/src/main/java/com/example/ecostyle/viewmodel/ProductViewModel.kt
Labels: sprint 4
